# Generated by Django 2.2 on 2019-11-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campname', models.CharField(blank=True, help_text='Campaign Name', max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('camptype', models.CharField(blank=True, help_text='Campaign Type', max_length=255, null=True)),
                ('campdate', models.DateField(blank=True, help_text='Campaign Type Date', null=True)),
                ('campperiodfrom', models.DateField(blank=True, help_text='Campaign  Period Type From Date', null=True)),
                ('campperiodto', models.DateField(blank=True, help_text='Campaign  Period Type To Date', null=True)),
                ('parameters', models.CharField(blank=True, help_text='Parameters To improve', max_length=255, null=True)),
                ('candidate', models.CharField(blank=True, help_text='Select Candidate', max_length=255, null=True)),
                ('prize', models.CharField(blank=True, help_text='Prize Type', max_length=255, null=True)),
                ('title', models.CharField(blank=True, help_text='Title 1', max_length=255, null=True)),
                ('title1', models.CharField(blank=True, help_text='Title 2', max_length=255, null=True)),
                ('title2', models.CharField(blank=True, help_text='Title 3', max_length=255, null=True)),
                ('prizetype', models.CharField(blank=True, help_text='Prize Type 1', max_length=255, null=True)),
                ('prizetype1', models.CharField(blank=True, help_text='Prize Type 2', max_length=255, null=True)),
                ('prizetype2', models.CharField(blank=True, help_text='Prize Type 3', max_length=255, null=True)),
                ('prizemoney', models.IntegerField(blank=True, help_text='Prize Money 1', null=True)),
                ('prizemoney1', models.IntegerField(blank=True, help_text='Prize Money 2', null=True)),
                ('prizemoney2', models.IntegerField(blank=True, help_text='Prize Money 3', null=True)),
                ('prizequantity', models.IntegerField(blank=True, help_text='Number oF Prize Quantity 1', null=True)),
                ('prizequantity1', models.IntegerField(blank=True, help_text='Number oF Prize Quantity 2', null=True)),
                ('prizequantity2', models.IntegerField(blank=True, help_text='Number oF Prize Quantity 3', null=True)),
                ('rank', models.CharField(blank=True, help_text='Rank 1', max_length=255, null=True)),
                ('rank1', models.CharField(blank=True, help_text='Rank 2', max_length=255, null=True)),
                ('rank2', models.CharField(blank=True, help_text='Rank 3', max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
