# Generated by Django 2.2 on 2019-11-11 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(help_text='Invoice Type', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(help_text='Date Of Invoice Add')),
                ('plate_number', models.CharField(help_text='Plate Number Of  Cars', max_length=255)),
                ('vin', models.CharField(help_text='Vin Number of Cars', max_length=255)),
                ('invoice_number', models.CharField(help_text='Vin Number of Cars', max_length=255)),
                ('price_net', models.FloatField(help_text='Net Price of cars Trips')),
                ('price_brutt', models.FloatField(help_text='brutto Price of cars Trips')),
                ('description', models.CharField(help_text='Details About Car', max_length=240)),
                ('invoice_type', models.ForeignKey(blank=True, help_text='Type of invoice select from field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='Cars.InvoiceType')),
            ],
        ),
    ]
