# Generated by Django 2.2 on 2019-11-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicetype',
            old_name='type',
            new_name='typee',
        ),
    ]
